### ISSUE TITLE
[bug] Pipelines em dev quebrando

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/queries-basedosdados-dev#7]
Após o último merge ( #6 ) as pipelines em `basedosdados-dev` passaram a quebrar. O erro que está apresentando no Prefect é o seguinte:
```
Task 'run_dbt_model': Exception encountered during task execution!
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/opt/venv/lib/python3.9/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipelines/utils/execute_dbt_model/tasks.py", line 54, in run_dbt_model
  File "/opt/venv/lib/python3.9/site-packages/dbt_client/dbt_client.py", line 270, in cli
    return self._run_sync(
  File "/opt/venv/lib/python3.9/site-packages/dbt_client/dbt_client.py", line 148, in _run_sync
    response_data = self._request(method, params=params)
  File "/opt/venv/lib/python3.9/site-packages/dbt_client/dbt_client.py", line 58, in _request
    return response.json()
  File "/opt/venv/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Seguindo o erro no Grafana, temos o seguinte log:
```
Error on request:
Traceback (most recent call last): 
    File \"/opt/venv/lib/python3.8/site-packages/werkzeug/serving.py\", line 335, in run_wsgi
        execute(self.server.app)
    File \"/opt/venv/lib/python3.8/site-packages/werkzeug/serving.py\", line 322, in execute
        application_iter = app(environ, start_response)
    File \"/opt/venv/lib/python3.8/site-packages/werkzeug/middleware/dispatcher.py\", line 78, in __call__
        return app(environ, start_response)
    File \"/opt/venv/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 187, in application
       resp = f(*args[:-2] + (request,))
    File \"/opt/venv/lib/python3.8/site-packages/dbt/task/rpc/server.py\", line 153, in handle_jsonrpc_request
       jsonrpc_response = ResponseManager.handle(
    File \"/opt/venv/lib/python3.8/site-packages/dbt/rpc/response_manager.py\", line 143, in handle
        result = cls.handle_valid_request(
    File \"/opt/venv/lib/python3.8/site-packages/dbt/rpc/response_manager.py\", line 88, in handle_valid_request
        return cls.handle_request(request, dispatcher)
    File \"/opt/venv/lib/python3.8/site-packages/jsonrpc/manager.py\", line 75, in handle_request
        responses = [r for r in cls._get_responses(rs, dispatcher, context)
TypeError: _get_responses() takes 3 positional arguments but 4 were given
```

**Comment by mfagundes** [comment]
Solucionado conforme este link: https://github.com/dbt-labs/dbt-core/issues/6487

A opção foi por limitar a versão do `json-rpc<1.14.0`, pois consideramos mais seguro do que atualizar o `DBT` para a versão `1.4.1`, que é a atual.
